"use client";

import {
  AndroidIcon,
  AngularIcon,
  AppleIcon,
  AstroIcon,
  Auth0Icon,
  AwsIcon,
  AzureIcon,
  BehanceIcon,
  BootstrapIcon,
  CloudflareIcon,
  CoinbaseIcon,
  Css3Icon,
  CypressIcon,
  DenoIcon,
  DiscordIcon,
  DockerIcon,
  DribbbleIcon,
  FigmaIcon,
  FirebaseIcon,
  FlutterIcon,
  FramerIcon,
  GitIcon,
  GitHubIcon,
  GitlabIcon,
  GraphqlIcon,
  Html5Icon,
  InstagramIcon,
  JavascriptIcon,
  KotlinIcon,
  LinkedInIcon,
  MediumIcon,
  MongodbIcon,
  NextjsIcon,
  NpmIcon,
  NodejsIcon,
  NotionIcon,
  NuxtIcon,
  OpenaiIcon,
  PaypalIcon,
  PhpIcon,
  PinterestIcon,
  PlanetScaleIcon,
  PnpmIcon,
  PrismaIcon,
  PythonIcon,
  ReactIcon,
  RedditIcon,
  ReduxIcon,
  RevolutIcon,
  RustIcon,
  SassIcon,
  SlackIcon,
  SnapchatIcon,
  SolidjsIcon,
  SpotifyIcon,
  SteamIcon,
  StorybookIcon,
  StripeIcon,
  SupabaseIcon,
  SvelteIcon,
  SwiftIcon,
  TailwindIcon,
  TelegramIcon,
  ThreejsIcon,
  TikTokIcon,
  TwitchIcon,
  TwitterIcon,
  TypeScriptIcon,
  UbuntuIcon,
  VercelIcon,
  ViteIcon,
  VscodeIcon,
  VueIcon,
  WhatsAppIcon,
  WindowsIcon,
  YouTubeIcon,
} from "@iconora/icons";
import type { AnimatedIconProps } from "@iconora/icons";

const components: Record<string, React.ComponentType<AnimatedIconProps>> = {
  android: AndroidIcon,
  angular: AngularIcon,
  apple: AppleIcon,
  astro: AstroIcon,
  auth0: Auth0Icon,
  aws: AwsIcon,
  azure: AzureIcon,
  behance: BehanceIcon,
  bootstrap: BootstrapIcon,
  cloudflare: CloudflareIcon,
  coinbase: CoinbaseIcon,
  css3: Css3Icon,
  cypress: CypressIcon,
  deno: DenoIcon,
  discord: DiscordIcon,
  docker: DockerIcon,
  dribbble: DribbbleIcon,
  figma: FigmaIcon,
  firebase: FirebaseIcon,
  flutter: FlutterIcon,
  framer: FramerIcon,
  git: GitIcon,
  github: GitHubIcon,
  gitlab: GitlabIcon,
  graphql: GraphqlIcon,
  html5: Html5Icon,
  instagram: InstagramIcon,
  javascript: JavascriptIcon,
  kotlin: KotlinIcon,
  linkedin: LinkedInIcon,
  medium: MediumIcon,
  mongodb: MongodbIcon,
  nextjs: NextjsIcon,
  npm: NpmIcon,
  nodejs: NodejsIcon,
  notion: NotionIcon,
  nuxt: NuxtIcon,
  openai: OpenaiIcon,
  paypal: PaypalIcon,
  php: PhpIcon,
  pinterest: PinterestIcon,
  planetscale: PlanetScaleIcon,
  pnpm: PnpmIcon,
  prisma: PrismaIcon,
  python: PythonIcon,
  react: ReactIcon,
  reddit: RedditIcon,
  redux: ReduxIcon,
  revolut: RevolutIcon,
  rust: RustIcon,
  sass: SassIcon,
  slack: SlackIcon,
  snapchat: SnapchatIcon,
  solidjs: SolidjsIcon,
  spotify: SpotifyIcon,
  steam: SteamIcon,
  storybook: StorybookIcon,
  stripe: StripeIcon,
  supabase: SupabaseIcon,
  svelte: SvelteIcon,
  swift: SwiftIcon,
  tailwind: TailwindIcon,
  telegram: TelegramIcon,
  threejs: ThreejsIcon,
  tiktok: TikTokIcon,
  twitch: TwitchIcon,
  twitter: TwitterIcon,
  typescript: TypeScriptIcon,
  ubuntu: UbuntuIcon,
  vercel: VercelIcon,
  vite: ViteIcon,
  vscode: VscodeIcon,
  vue: VueIcon,
  whatsapp: WhatsAppIcon,
  windows: WindowsIcon,
  youtube: YouTubeIcon,
};

export function AnimatedIcon({
  slug,
  size = 24,
  ...props
}: { slug: string } & Partial<AnimatedIconProps>) {
  const Component = components[slug];
  if (!Component) return null;
  return <Component size={size} {...props} />;
}
